{
  "name": "tryumph",
  "version": "0.0.0-semantic-release",
  "description": "Bring the \"Umph\" to the javascript's async error handling",
  "files": ["dist"],
  "types": "./dist/tryumph.d.ts",
  "exports": {
    ".": {
      "import": {
        "types": "./dist/tryumph.d.ts",
        "default": "./dist/tryumph.esm.mjs"
      },
      "require": {
        "types": "./dist/tryumph.d.ts",
        "default": "./dist/tryumph.common.js"
      }
    }
  },
  "scripts": {
    "prepare": "npm run clean && npm run build",
    "clean": "ts-node ./scripts/clean.ts",
    "lint": "eslint .",
    "test": "jest",
    "test-cov": "npm run test -- --coverage",
    "test-coveralls": "npm run test-cov && node ./scripts/coveralls.mjs",
    "build": "rollup -c ./rollup.config.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/rzvxa/tryumph.git"
  },
  "keywords": [
    "try",
    "async",
    "errorHandling",
    "dontThrow",
    "fault tolerant",
    "production",
    "node.js",
    "typescript",
    "strong",
    "rust",
    "rust like",
    "rust error handling",
    "go",
    "go like",
    "go error handling",
    "tryumph"
  ],
  "author": "rzvxa",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/rzvxa/tryumph/issues"
  },
  "homepage": "https://rzvxa.github.io/tryumph/",
  "devDependencies": {
    "@rollup/plugin-node-resolve": "^15.2.3",
    "@rollup/plugin-terser": "^0.4.4",
    "@rollup/plugin-typescript": "^11.1.5",
    "@types/jest": "^29.5.11",
    "@typescript-eslint/eslint-plugin": "^6.16.0",
    "@typescript-eslint/parser": "^6.16.0",
    "coveralls": "^3.1.1",
    "eslint": "^8.56.0",
    "jest": "^29.7.0",
    "rollup": "^4.9.2",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.2",
    "tslib": "^2.6.2",
    "typedoc": "^0.25.4",
    "typescript": "^5.3.3"
  },
  "engines": {
    "node": "^16.20.2"
  },
  "engineStrict": true,
  "dependencies": {
    "dwait": "^1.1.3"
  }
}
